### ISSUE TITLE
Fail to indent with error "AttributeError: 'module' object has no attribute 'messages'"

### ISSUE THREAD

**Issue by gMit03** [alek-sys/sublimetext_indentxml#102]
Hi, 
when i try run via command pallete, the following code is in the log and the code doesn't format.
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
  File ".\indentxml.py", line 52, in run
  File ".\indentxml.py", line 106, in indent
AttributeError: 'module' object has no attribute 'messages'

Seems like i'm encountering an error. Could you assist??

**Comment by alek-sys** [comment]
Please check the new version.
