### ISSUE TITLE
Don't work in sublime text 2

### ISSUE THREAD

**Issue by morojosa** [alek-sys/sublimetext_indentxml#67]
Hello,

Thanks for best job with this plugin.

The XML have 491800 characters.

The error is this:

Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
  File ".\indentxml.py", line 49, in run
  File ".\indentxml.py", line 96, in indent
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 491786

Regards and @goto thanks

**Comment by timothyclifford** [comment]
Same...
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "indentxml in C:\Users\tim.clifford\AppData\Roaming\Sublime Text 3\Installed Packages\Indent XML.sublime-package", line 44, in run
  File "indentxml in C:\Users\tim.clifford\AppData\Roaming\Sublime Text 3\Installed Packages\Indent XML.sublime-package", line 77, in indent
  File "indentxml in C:\Users\tim.clifford\AppData\Roaming\Sublime Text 3\Installed Packages\Indent XML.sublime-package", line 96, in indent
  File "indentxml in C:\Users\tim.clifford\AppData\Roaming\Sublime Text 3\Installed Packages\Indent XML.sublime-package", line 93, in indent
  File "./xml/dom/minidom.py", line 1970, in parseString
  File "./xml/dom/expatbuilder.py", line 926, in parseString
  File "./xml/dom/expatbuilder.py", line 221, in parseString
xml.parsers.expat.ExpatError: undefined entity: line 1, column 77
```

**Comment by iBobik** [comment]
Same
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "indentxml in /Users/Bobik/Library/Application Support/Sublime Text 3/Installed Packages/Indent XML.sublime-package", line 49, in run
  File "indentxml in /Users/Bobik/Library/Application Support/Sublime Text 3/Installed Packages/Indent XML.sublime-package", line 77, in indent
  File "indentxml in /Users/Bobik/Library/Application Support/Sublime Text 3/Installed Packages/Indent XML.sublime-package", line 96, in indent
  File "indentxml in /Users/Bobik/Library/Application Support/Sublime Text 3/Installed Packages/Indent XML.sublime-package", line 93, in indent
  File "./xml/dom/minidom.py", line 1970, in parseString
  File "./xml/dom/expatbuilder.py", line 926, in parseString
  File "./xml/dom/expatbuilder.py", line 221, in parseString
xml.parsers.expat.ExpatError: mismatched tag: line 1, column 285
```

on HTML snippet:
```
<div class="field field-name-field-photos field-type-image field-label-hidden"><div class="field-items"><div class="field-item even"><img src="https://example.com/sites/default/files/styles/thumbnail/public/tour-photos/bsoz-iv/pokoj-11.jpg?itok=v_qDYn85" width="100" height="75"></div><div class="field-item odd"><img src="https://example.com/sites/default/files/styles/thumbnail/public/tour-photos/bsoz-iv/ivan-p2.5.jpg?itok=j6BcdN9P" width="100" height="67"></div><div class="field-item even"><img src="https://example.com/sites/default/files/styles/thumbnail/public/tour-photos/bsoz-iv/ivan-2.jpg?itok=8ZpgrfF2" width="67" height="100"></div><div class="field-item odd"><img src="https://example.com/sites/default/files/styles/thumbnail/public/tour-photos/bsoz-iv/ivan-p2.1.jpg?itok=Pc0poyqW" width="100" height="67"></div><div class="field-item even"><img src="https://example.com/sites/default/files/styles/thumbnail/public/tour-photos/bsoz-iv/ivan1.jpg?itok=1yNM8e0L" width="100" height="67"></div><div class="field-item odd"><img src="https://example.com/sites/default/files/styles/thumbnail/public/tour-photos/bsoz-iv/ivan-z-ulice.jpg?itok=TLNsh3O0" width="100" height="75"></div><div class="field-item even"><img src="https://example.com/sites/default/files/styles/thumbnail/public/tour-photos/bsoz-iv/fotografia0809.jpg?itok=yAY3g7Li" width="100" height="75"></div></div></div>
```

**Comment by cheneysan** [comment]
Possible workaround:
File -> Reopen with Encoding -> UTF-8
Ctrl+Shift+P -> Indent XML

**Comment by alek-sys** [comment]
Hi all,
Cannot comment the original question because there is no sample file attached.

Regarding HTML snippet - the given example is not a valid XML (img tags are not closed), please use XHTML to be able to use this plugin.

Thanks, Alexey.
