### ISSUE TITLE
doesn't work under Linux

### ISSUE THREAD

**Issue by Magistrate-zz** [alek-sys/sublimetext_indentxml#9]
Hi,

your package works great below Windows. But below Linux I got this error message on the console:

Traceback (most recent call last):
  File "./sublime_plugin.py", line 351, in run_
  File "./indentxml.py", line 32, in run
  File "./indentxml.py", line 48, in indentxml
  File ".\xml\dom\minidom.py", line 1927, in parseString
  File ".\xml\dom\expatbuilder.py", line 32, in <module>
  File ".\xml\parsers\expat.py", line 4, in <module>
ImportError: No module named pyexpat

I'm using the latest build (Build 2165).

Any idea?

Cheers,
Magistrate

**Comment by arenaux** [comment]
And for 64bit system : "usr/lib64/python2.6" instead of "usr/lib/python2.6"

**Comment by skualos** [comment]
If this did not work for you, try https://github.com/alek-sys/sublimetext_indentxml/issues/16#issuecomment-78509626
Worked for me on Ubuntu 14.04 x64

**Comment by molecular** [comment]
for archlinux try https://aur.archlinux.org/packages/python26/
